# Generated by Django 5.2.1 on 2025-05-30 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr', models.FloatField(verbose_name='BMR')),
                ('tdee', models.FloatField(verbose_name='TDEE')),
                ('protein', models.FloatField(verbose_name='Белки')),
                ('fat', models.FloatField(verbose_name='Жиры')),
                ('carbs', models.FloatField(verbose_name='Углеводы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат расчёта',
                'verbose_name_plural': 'Результаты расчётов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/', verbose_name='Изображение')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.goal', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Рекомендация по питанию',
                'verbose_name_plural': 'Рекомендации по питанию',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название упражнения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('intensity', models.CharField(max_length=50, verbose_name='Интенсивность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_images/', verbose_name='Изображение')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.goal', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=70, verbose_name='Вес (кг)')),
                ('height', models.IntegerField(default=170, verbose_name='Рост (см)')),
                ('age', models.IntegerField(default=25, verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол')),
                ('activity_level', models.FloatField(default=1.2, verbose_name='Уровень активности')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='FavoriteFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.foodrecommendation', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Избранное блюдо',
                'verbose_name_plural': 'Избранные блюда',
                'unique_together': {('user', 'food')},
            },
        ),
    ]
